"""
Validation schemas package.

This package contains the validation schemas used for input/output validation
in the application. These schemas define the expected structure of data for
API requests and responses.

Note: Entity and state tracking schemas have been removed.
Pipeline tracking is now record-agnostic using pipeline_id only.
"""

# Import credential schemas
from .credential_schemas import (
    APIKeyCredentials,
    AzureServicePrincipalCredentials,
    BaseCredentialSchema,
    BasicAuthCredentials,
    CredentialData,
    CustomCredentials,
    DatabaseCredentials,
    ExternalCredentialCreate,
    ExternalCredentialRead,
    ExternalCredentialUpdate,
    OAuthCredentials,
    deserialize_credentials,
    serialize_credentials,
)

# Error message schema removed - was too complex for V2
from .metric_model import (
    Metric,
    QueueMetric,
)

# Import tenant schemas
from .tenant_schemas import (
    ApiConfigSchema,
    BaseTenantConfigSchema,
    CustomTenantConfigSchema,
    DatabaseConfigSchema,
    EnvironmentConfigSchema,
    ProcessingConfigSchema,
    SecurityConfigSchema,
    TenantConfigData,
    TenantCreate,
    TenantRead,
    TenantUpdate,
    deserialize_tenant_config,
    serialize_tenant_config,
)

# Processing error schema removed - not needed for V2
# Tenant schemas now generated by factory functions

# Note: Canonical schemas are intentionally not imported here as they are part of
# commercial add-ons and not included in the open-source release.

__all__ = [
    # Metric schemas
    "Metric",
    "QueueMetric",
    # Credential schemas
    "BaseCredentialSchema",
    "OAuthCredentials",
    "APIKeyCredentials",
    "BasicAuthCredentials",
    "AzureServicePrincipalCredentials",
    "DatabaseCredentials",
    "CustomCredentials",
    "CredentialData",
    "ExternalCredentialCreate",
    "ExternalCredentialRead",
    "ExternalCredentialUpdate",
    "serialize_credentials",
    "deserialize_credentials",
    # Tenant schemas
    "BaseTenantConfigSchema",
    "DatabaseConfigSchema",
    "ProcessingConfigSchema",
    "ApiConfigSchema",
    "SecurityConfigSchema",
    "EnvironmentConfigSchema",
    "CustomTenantConfigSchema",
    "TenantConfigData",
    "TenantCreate",
    "TenantRead",
    "TenantUpdate",
    "serialize_tenant_config",
    "deserialize_tenant_config",
    # Note: CRUD schemas are now generated by factory functions in utils.schema_factory
]
