"""Add external_access_tokens table for encrypted token storage

Revision ID: 1be9ee71a8b5
Revises: 1382c3ca4535
Create Date: 2025-06-09 15:37:49.243969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be9ee71a8b5'
down_revision: Union[str, None] = '1382c3ca4535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_access_tokens',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_expires_at', 'external_access_tokens', ['expires_at'], unique=False)
    op.create_index('ix_token_system_name', 'external_access_tokens', ['system_name'], unique=False)
    op.create_index('ix_token_tenant_id', 'external_access_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_token_tenant_system', 'external_access_tokens', ['tenant_id', 'system_name'], unique=False)
    op.alter_column('external_credentials', 'encrypted_credentials',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_credentials', 'encrypted_credentials',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.drop_index('ix_token_tenant_system', table_name='external_access_tokens')
    op.drop_index('ix_token_tenant_id', table_name='external_access_tokens')
    op.drop_index('ix_token_system_name', table_name='external_access_tokens')
    op.drop_index('ix_token_expires_at', table_name='external_access_tokens')
    op.drop_table('external_access_tokens')
    # ### end Alembic commands ###
