"""initial_migration_with_all_current_models

Revision ID: 2326b6953c92
Revises: 
Create Date: 2025-06-12 11:27:01.922778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from api_exchange_core.db import EncryptedBinary, JSON

# revision identifiers, used by Alembic.
revision: str = '2326b6953c92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=200), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=200), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tenant_config', JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index('ix_tenant_customer_name', 'tenant', ['customer_name'], unique=False)
    op.create_index('ix_tenant_is_active', 'tenant', ['is_active'], unique=False)
    op.create_index('ix_tenant_tenant_id', 'tenant', ['tenant_id'], unique=False)
    op.create_table('api_token_usage_log',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('usage_context', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_correlation_id', 'api_token_usage_log', ['correlation_id'], unique=False)
    op.create_index('ix_api_usage_operation', 'api_token_usage_log', ['operation'], unique=False)
    op.create_index('ix_api_usage_tenant_operation', 'api_token_usage_log', ['tenant_id', 'api_provider', 'operation'], unique=False)
    op.create_index('ix_api_usage_tenant_provider', 'api_token_usage_log', ['tenant_id', 'api_provider'], unique=False)
    op.create_index('ix_api_usage_token_id', 'api_token_usage_log', ['token_id'], unique=False)
    op.create_index('ix_api_usage_used_at', 'api_token_usage_log', ['used_at'], unique=False)
    op.create_table('api_tokens',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_token', EncryptedBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generation_context', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_api_token_hash')
    )
    op.create_index('ix_api_token_created_at', 'api_tokens', ['created_at'], unique=False)
    op.create_index('ix_api_token_expires_at', 'api_tokens', ['expires_at'], unique=False)
    op.create_index('ix_api_token_last_used', 'api_tokens', ['last_used_at'], unique=False)
    op.create_index('ix_api_token_tenant_active', 'api_tokens', ['tenant_id', 'api_provider', 'is_active'], unique=False)
    op.create_index('ix_api_token_tenant_provider', 'api_tokens', ['tenant_id', 'api_provider'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id', 'version', name='uq_entity_tenant_source_external_id_version')
    )
    op.create_index('ix_entity_content_hash', 'entity', ['content_hash'], unique=False)
    op.create_index('ix_entity_external_id', 'entity', ['external_id'], unique=False)
    op.create_index('ix_entity_tenant', 'entity', ['tenant_id'], unique=False)
    op.create_index('ix_entity_tenant_external_id', 'entity', ['tenant_id', 'external_id'], unique=False)
    op.create_index('ix_entity_tenant_source', 'entity', ['tenant_id', 'source'], unique=False)
    op.create_index('ix_entity_tenant_source_hash', 'entity', ['tenant_id', 'source', 'content_hash'], unique=False)
    op.create_index('ix_entity_tenant_type', 'entity', ['tenant_id', 'canonical_type'], unique=False)
    op.create_table('external_credentials',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_credentials', EncryptedBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'system_name', name='uq_credential_tenant_system')
    )
    op.create_index('ix_credential_system_name', 'external_credentials', ['system_name'], unique=False)
    op.create_index('ix_credential_tenant_id', 'external_credentials', ['tenant_id'], unique=False)
    op.create_table('token_coordination',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('api_provider', sa.String(length=255), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'api_provider')
    )
    op.create_index('ix_token_coordination_attempt_count', 'token_coordination', ['attempt_count'], unique=False)
    op.create_index('ix_token_coordination_expires_at', 'token_coordination', ['expires_at'], unique=False)
    op.create_index('ix_token_coordination_locked_at', 'token_coordination', ['locked_at'], unique=False)
    op.create_table('processingerror',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('error_type_code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('processing_step', sa.String(length=100), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_error_entity_id', 'processingerror', ['entity_id'], unique=False)
    op.create_index('ix_processing_error_tenant', 'processingerror', ['tenant_id'], unique=False)
    op.create_index('ix_processing_error_type', 'processingerror', ['error_type_code'], unique=False)
    op.create_table('statetransition',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=False),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transition_type', sa.Enum('NORMAL', 'ERROR', 'RECOVERY', 'MANUAL', 'TIMEOUT', 'RETRY', name='transitiontypeenum', native_enum=False), nullable=False),
    sa.Column('processor_data', JSON(), nullable=True, comment='Processor-specific data about the transition'),
    sa.Column('queue_source', sa.String(length=100), nullable=True, comment='Queue from which the message was received'),
    sa.Column('queue_destination', sa.String(length=100), nullable=True, comment='Queue to which the message was sent'),
    sa.Column('transition_duration', sa.Integer(), nullable=True, comment='Time (in ms) spent in the previous state'),
    sa.Column('sequence_number', sa.Integer(), nullable=True, comment='Sequence number for ordering transitions'),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_state_transition_entity_id', 'statetransition', ['entity_id'], unique=False)
    op.create_index('ix_state_transition_entity_tenant', 'statetransition', ['entity_id', 'tenant_id'], unique=False)
    op.create_index('ix_state_transition_sequence', 'statetransition', ['entity_id', 'sequence_number'], unique=False)
    op.create_index('ix_state_transition_tenant', 'statetransition', ['tenant_id'], unique=False)
    op.create_index('ix_state_transition_to_state', 'statetransition', ['to_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_state_transition_to_state', table_name='statetransition')
    op.drop_index('ix_state_transition_tenant', table_name='statetransition')
    op.drop_index('ix_state_transition_sequence', table_name='statetransition')
    op.drop_index('ix_state_transition_entity_tenant', table_name='statetransition')
    op.drop_index('ix_state_transition_entity_id', table_name='statetransition')
    op.drop_table('statetransition')
    op.drop_index('ix_processing_error_type', table_name='processingerror')
    op.drop_index('ix_processing_error_tenant', table_name='processingerror')
    op.drop_index('ix_processing_error_entity_id', table_name='processingerror')
    op.drop_table('processingerror')
    op.drop_index('ix_token_coordination_locked_at', table_name='token_coordination')
    op.drop_index('ix_token_coordination_expires_at', table_name='token_coordination')
    op.drop_index('ix_token_coordination_attempt_count', table_name='token_coordination')
    op.drop_table('token_coordination')
    op.drop_index('ix_credential_tenant_id', table_name='external_credentials')
    op.drop_index('ix_credential_system_name', table_name='external_credentials')
    op.drop_table('external_credentials')
    op.drop_index('ix_entity_tenant_type', table_name='entity')
    op.drop_index('ix_entity_tenant_source_hash', table_name='entity')
    op.drop_index('ix_entity_tenant_source', table_name='entity')
    op.drop_index('ix_entity_tenant_external_id', table_name='entity')
    op.drop_index('ix_entity_tenant', table_name='entity')
    op.drop_index('ix_entity_external_id', table_name='entity')
    op.drop_index('ix_entity_content_hash', table_name='entity')
    op.drop_table('entity')
    op.drop_index('ix_api_token_tenant_provider', table_name='api_tokens')
    op.drop_index('ix_api_token_tenant_active', table_name='api_tokens')
    op.drop_index('ix_api_token_last_used', table_name='api_tokens')
    op.drop_index('ix_api_token_expires_at', table_name='api_tokens')
    op.drop_index('ix_api_token_created_at', table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index('ix_api_usage_used_at', table_name='api_token_usage_log')
    op.drop_index('ix_api_usage_token_id', table_name='api_token_usage_log')
    op.drop_index('ix_api_usage_tenant_provider', table_name='api_token_usage_log')
    op.drop_index('ix_api_usage_tenant_operation', table_name='api_token_usage_log')
    op.drop_index('ix_api_usage_operation', table_name='api_token_usage_log')
    op.drop_index('ix_api_usage_correlation_id', table_name='api_token_usage_log')
    op.drop_table('api_token_usage_log')
    op.drop_index('ix_tenant_tenant_id', table_name='tenant')
    op.drop_index('ix_tenant_is_active', table_name='tenant')
    op.drop_index('ix_tenant_customer_name', table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
