"""initial release

Revision ID: 5dd109a62f3f
Revises: 
Create Date: 2025-07-10 21:23:32.883885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api_exchange_core.db.db_base import EncryptedBinary, JSON

# revision identifiers, used by Alembic.
revision: str = '5dd109a62f3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('token_value', EncryptedBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_token_lookup', 'api_tokens', ['tenant_id', 'api_provider', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_tokens_expires_at'), 'api_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_table('external_credentials',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('credential_data', EncryptedBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credential_lookup', 'external_credentials', ['tenant_id', 'system_name'], unique=True)
    op.create_index(op.f('ix_external_credentials_tenant_id'), 'external_credentials', ['tenant_id'], unique=False)
    op.create_table('pipeline_definition',
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('pipeline_structure', JSON(), nullable=False),
    sa.Column('capture_messages', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_def_lookup', 'pipeline_definition', ['pipeline_name', 'is_active'], unique=False)
    op.create_index('ix_pipeline_def_tenant', 'pipeline_definition', ['tenant_id', 'pipeline_name'], unique=False)
    op.create_index(op.f('ix_pipeline_definition_pipeline_name'), 'pipeline_definition', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_pipeline_definition_tenant_id'), 'pipeline_definition', ['tenant_id'], unique=False)
    op.create_table('pipeline_execution',
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_source', sa.String(length=200), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_step', sa.String(length=100), nullable=True),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_exec_correlation', 'pipeline_execution', ['correlation_id'], unique=False)
    op.create_index('ix_pipeline_exec_lookup', 'pipeline_execution', ['tenant_id', 'pipeline_id', 'status'], unique=False)
    op.create_index('ix_pipeline_exec_time', 'pipeline_execution', ['started_at', 'completed_at'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_correlation_id'), 'pipeline_execution', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_pipeline_id'), 'pipeline_execution', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_tenant_id'), 'pipeline_execution', ['tenant_id'], unique=False)
    op.create_table('pipeline_message',
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('message_payload', JSON(), nullable=True),
    sa.Column('message_size_bytes', sa.Integer(), nullable=True),
    sa.Column('source_queue', sa.String(length=100), nullable=True),
    sa.Column('target_queue', sa.String(length=100), nullable=True),
    sa.Column('is_sanitized', sa.Boolean(), nullable=False),
    sa.Column('sanitization_rules', JSON(), nullable=True),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_message_step_id'), 'pipeline_message', ['step_id'], unique=False)
    op.create_index('ix_pipeline_msg_lookup', 'pipeline_message', ['tenant_id', 'execution_id'], unique=False)
    op.create_index('ix_pipeline_msg_step', 'pipeline_message', ['step_id', 'message_type'], unique=False)
    op.create_table('pipeline_step',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('processor_name', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.Column('output_queues', JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_step_execution', 'pipeline_step', ['execution_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_pipeline_step_execution_id'), 'pipeline_step', ['execution_id'], unique=False)
    op.create_index('ix_pipeline_step_lookup', 'pipeline_step', ['tenant_id', 'pipeline_id', 'step_name'], unique=False)
    op.create_index('ix_pipeline_step_message', 'pipeline_step', ['message_id'], unique=False)
    op.create_table('pipeline_step_definition',
    sa.Column('pipeline_definition_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('processor_name', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('input_trigger', sa.String(length=100), nullable=True),
    sa.Column('output_queues', JSON(), nullable=True),
    sa.Column('step_order', sa.String(length=10), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('context', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_step_def_lookup', 'pipeline_step_definition', ['pipeline_name', 'step_name'], unique=False)
    op.create_index(op.f('ix_pipeline_step_definition_pipeline_definition_id'), 'pipeline_step_definition', ['pipeline_definition_id'], unique=False)
    op.create_index(op.f('ix_pipeline_step_definition_tenant_id'), 'pipeline_step_definition', ['tenant_id'], unique=False)
    op.create_index('ix_pipeline_step_function', 'pipeline_step_definition', ['function_name'], unique=False)
    op.create_index('ix_pipeline_step_tenant', 'pipeline_step_definition', ['tenant_id', 'pipeline_name'], unique=False)
    op.create_table('tenant',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_lookup', 'tenant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_tenant_id'), 'tenant', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_tenant_id'), table_name='tenant')
    op.drop_index('ix_tenant_lookup', table_name='tenant')
    op.drop_table('tenant')
    op.drop_index('ix_pipeline_step_tenant', table_name='pipeline_step_definition')
    op.drop_index('ix_pipeline_step_function', table_name='pipeline_step_definition')
    op.drop_index(op.f('ix_pipeline_step_definition_tenant_id'), table_name='pipeline_step_definition')
    op.drop_index(op.f('ix_pipeline_step_definition_pipeline_definition_id'), table_name='pipeline_step_definition')
    op.drop_index('ix_pipeline_step_def_lookup', table_name='pipeline_step_definition')
    op.drop_table('pipeline_step_definition')
    op.drop_index('ix_pipeline_step_message', table_name='pipeline_step')
    op.drop_index('ix_pipeline_step_lookup', table_name='pipeline_step')
    op.drop_index(op.f('ix_pipeline_step_execution_id'), table_name='pipeline_step')
    op.drop_index('ix_pipeline_step_execution', table_name='pipeline_step')
    op.drop_table('pipeline_step')
    op.drop_index('ix_pipeline_msg_step', table_name='pipeline_message')
    op.drop_index('ix_pipeline_msg_lookup', table_name='pipeline_message')
    op.drop_index(op.f('ix_pipeline_message_step_id'), table_name='pipeline_message')
    op.drop_table('pipeline_message')
    op.drop_index(op.f('ix_pipeline_execution_tenant_id'), table_name='pipeline_execution')
    op.drop_index(op.f('ix_pipeline_execution_pipeline_id'), table_name='pipeline_execution')
    op.drop_index(op.f('ix_pipeline_execution_correlation_id'), table_name='pipeline_execution')
    op.drop_index('ix_pipeline_exec_time', table_name='pipeline_execution')
    op.drop_index('ix_pipeline_exec_lookup', table_name='pipeline_execution')
    op.drop_index('ix_pipeline_exec_correlation', table_name='pipeline_execution')
    op.drop_table('pipeline_execution')
    op.drop_index(op.f('ix_pipeline_definition_tenant_id'), table_name='pipeline_definition')
    op.drop_index(op.f('ix_pipeline_definition_pipeline_name'), table_name='pipeline_definition')
    op.drop_index('ix_pipeline_def_tenant', table_name='pipeline_definition')
    op.drop_index('ix_pipeline_def_lookup', table_name='pipeline_definition')
    op.drop_table('pipeline_definition')
    op.drop_index(op.f('ix_external_credentials_tenant_id'), table_name='external_credentials')
    op.drop_index('ix_credential_lookup', table_name='external_credentials')
    op.drop_table('external_credentials')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_expires_at'), table_name='api_tokens')
    op.drop_index('ix_api_token_lookup', table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
