"""drop correlation_id

Revision ID: 73f52a1a020a
Revises: a8be8f6d567b
Create Date: 2025-06-26 20:26:02.204980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f52a1a020a'
down_revision: Union[str, None] = 'a8be8f6d567b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_state_history_correlation_id'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_tenant_correlation'), table_name='pipeline_state_history')
    op.create_index('ix_pipeline_state_tenant_timeline', 'pipeline_state_history', ['tenant_id', 'log_timestamp'], unique=False)
    op.drop_column('pipeline_state_history', 'correlation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_state_history', sa.Column('correlation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index('ix_pipeline_state_tenant_timeline', table_name='pipeline_state_history')
    op.create_index(op.f('ix_pipeline_state_tenant_correlation'), 'pipeline_state_history', ['tenant_id', 'correlation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_correlation_id'), 'pipeline_state_history', ['correlation_id'], unique=False)
    # ### end Alembic commands ###
