"""add_pipeline_id_and_pipeline_json_to_entity

Revision ID: 8a802f3e7652
Revises: 8c1bec1b2b99
Create Date: 2025-07-01 21:09:18.870637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a802f3e7652'
down_revision: Union[str, None] = '8c1bec1b2b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('pipeline_id', sa.String(length=36), nullable=True))
    op.add_column('entity', sa.Column('pipeline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_entity_pipeline_id', 'entity', ['pipeline_id'], unique=False)
    op.create_index('ix_entity_tenant_pipeline_id', 'entity', ['tenant_id', 'pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_tenant_pipeline_id', table_name='entity')
    op.drop_index('ix_entity_pipeline_id', table_name='entity')
    op.drop_column('entity', 'pipeline_json')
    op.drop_column('entity', 'pipeline_id')
    # ### end Alembic commands ###
