"""add_pipeline_name_to_entity_and_pipeline_state_history

Revision ID: 8c1bec1b2b99
Revises: e85a43828f74
Create Date: 2025-07-01 20:43:11.697506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1bec1b2b99'
down_revision: Union[str, None] = 'e85a43828f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('pipeline_name', sa.String(length=100), nullable=True))
    op.create_index('ix_entity_pipeline_name', 'entity', ['pipeline_name'], unique=False)
    op.create_index('ix_entity_tenant_pipeline', 'entity', ['tenant_id', 'pipeline_name'], unique=False)
    op.add_column('pipeline_state_history', sa.Column('pipeline_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_pipeline_state_history_pipeline_name'), 'pipeline_state_history', ['pipeline_name'], unique=False)
    op.create_index('ix_pipeline_state_pipeline_name', 'pipeline_state_history', ['pipeline_name', 'log_timestamp'], unique=False)
    op.create_index('ix_pipeline_state_tenant_pipeline', 'pipeline_state_history', ['tenant_id', 'pipeline_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_state_tenant_pipeline', table_name='pipeline_state_history')
    op.drop_index('ix_pipeline_state_pipeline_name', table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_pipeline_name'), table_name='pipeline_state_history')
    op.drop_column('pipeline_state_history', 'pipeline_name')
    op.drop_index('ix_entity_tenant_pipeline', table_name='entity')
    op.drop_index('ix_entity_pipeline_name', table_name='entity')
    op.drop_column('entity', 'pipeline_name')
    # ### end Alembic commands ###
