"""Remove pipeline tracking columns

Revision ID: a245474fccb0
Revises: 8a802f3e7652
Create Date: 2025-07-03 22:06:38.291550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a245474fccb0'
down_revision: Union[str, None] = '8a802f3e7652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_pipeline_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_pipeline_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_tenant_pipeline'), table_name='entity')
    op.drop_index(op.f('ix_entity_tenant_pipeline_id'), table_name='entity')
    op.drop_column('entity', 'pipeline_name')
    op.drop_column('entity', 'pipeline_id')
    op.drop_column('entity', 'pipeline_json')
    op.drop_index(op.f('ix_pipeline_state_history_pipeline_name'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_pipeline_name'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_tenant_pipeline'), table_name='pipeline_state_history')
    op.drop_column('pipeline_state_history', 'pipeline_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_state_history', sa.Column('pipeline_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_pipeline_state_tenant_pipeline'), 'pipeline_state_history', ['tenant_id', 'pipeline_name'], unique=False)
    op.create_index(op.f('ix_pipeline_state_pipeline_name'), 'pipeline_state_history', ['pipeline_name', 'log_timestamp'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_pipeline_name'), 'pipeline_state_history', ['pipeline_name'], unique=False)
    op.add_column('entity', sa.Column('pipeline_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('pipeline_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('pipeline_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_entity_tenant_pipeline_id'), 'entity', ['tenant_id', 'pipeline_id'], unique=False)
    op.create_index(op.f('ix_entity_tenant_pipeline'), 'entity', ['tenant_id', 'pipeline_name'], unique=False)
    op.create_index(op.f('ix_entity_pipeline_name'), 'entity', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_entity_pipeline_id'), 'entity', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###
