"""add StateTransitionTable

Revision ID: a8be8f6d567b
Revises: 19b46e207c8b
Create Date: 2025-06-25 20:47:04.294007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8be8f6d567b'
down_revision: Union[str, None] = '19b46e207c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_state_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('processor_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_queue', sa.String(length=100), nullable=True),
    sa.Column('destination_queue', sa.String(length=100), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('message_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('log_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_state_entity_timeline', 'pipeline_state_history', ['entity_id', 'log_timestamp'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_correlation_id'), 'pipeline_state_history', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_entity_id'), 'pipeline_state_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_log_timestamp'), 'pipeline_state_history', ['log_timestamp'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_processor_name'), 'pipeline_state_history', ['processor_name'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_status'), 'pipeline_state_history', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_tenant_id'), 'pipeline_state_history', ['tenant_id'], unique=False)
    op.create_index('ix_pipeline_state_processor_status', 'pipeline_state_history', ['processor_name', 'status'], unique=False)
    op.create_index('ix_pipeline_state_tenant_correlation', 'pipeline_state_history', ['tenant_id', 'correlation_id'], unique=False)
    op.create_index('ix_pipeline_state_timeline', 'pipeline_state_history', ['log_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_state_timeline', table_name='pipeline_state_history')
    op.drop_index('ix_pipeline_state_tenant_correlation', table_name='pipeline_state_history')
    op.drop_index('ix_pipeline_state_processor_status', table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_tenant_id'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_status'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_processor_name'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_log_timestamp'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_entity_id'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_correlation_id'), table_name='pipeline_state_history')
    op.drop_index('ix_pipeline_state_entity_timeline', table_name='pipeline_state_history')
    op.drop_table('pipeline_state_history')
    # ### end Alembic commands ###
