"""add_pipeline_id_to_pipeline_state_history

Revision ID: e85a43828f74
Revises: 85a558efd924
Create Date: 2025-06-26 22:47:06.225407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85a43828f74'
down_revision: Union[str, None] = '85a558efd924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_state_history', sa.Column('pipeline_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_pipeline_state_history_pipeline_id'), 'pipeline_state_history', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_state_history_pipeline_id'), table_name='pipeline_state_history')
    op.drop_column('pipeline_state_history', 'pipeline_id')
    # ### end Alembic commands ###
