version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: e2e_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    # No volumes - data is ephemeral
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c shared_buffers=256MB -c max_connections=200 -c log_statement=all -c log_min_duration_statement=0

  # Azurite for Azure Storage emulation
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    container_name: e2e_azurite
    ports:
      - "${AZURITE_BLOB_PORT:-10000}:10000"  # Blob
      - "${AZURITE_QUEUE_PORT:-10001}:10001"  # Queue
      - "${AZURITE_TABLE_PORT:-10002}:10002"  # Table
    command: azurite --queueHost 0.0.0.0 --blobHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck
    healthcheck:
      test: nc -z 127.0.0.1 10001
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    name: e2e_network